### ISSUE TITLE
[Bug] SecuritySchemeHttp is missing scheme-parameter

### ISSUE THREAD

**Issue by Elewyth** [biocad/servant-openapi3#7]
When building a specification using SecuritySchemeHttp as SecuritySchemeType, I noticed that it is not possible to specify any additional parameters, as it is, for example, with SecuritySchemeApiKey. This leads to a spec being generated that fails the schema-validation of openapi3: https://swagger.io/specification/#security-requirement-object

The field "scheme" is required for type http. Additionally, it would be nice to specify the optional field "bearerFormat" when providing these parameters for http.

**Comment by maksbotan** [comment]
Hi! Thanks for checking out servant-openapi3 :)

The problem actually lies in the `openapi3` package, and there's an open PR to fix that: https://github.com/biocad/openapi3/pull/10

There are a couple of minor corrections to be made, after which I'll update the package.

**Comment by Elewyth** [comment]
Oh yeah, you are right, thanks for pointing me into the right direction! Glad this is already nearly fixed :).

**Comment by maksbotan** [comment]
This was fixed in https://github.com/biocad/openapi3/pull/10 and is on Hackage as `openapi3-3.0.2.0`.
